global:

  log:
    level: INFO  # DEBUG, INFO, WARNING, ERROR

  ways:
    ways_easy: &WAYS_EASY [ E, S ]
    ways_normal: &WAYS_NORMAL [ E, SE, S ]
    ways_ALL: &WAYS_ALL [ E, SE, S, SW, W, NW, N, NE ]

  lang:
    es:
      letters: &LETTERS_ES [A, B, C, D, E, F, G, H, I, J, K, L, M, N, Ñ, O, P, Q, R, S, T, U, V, W, X, Y, Z]
      # https://es.wikipedia.org/wiki/Frecuencia_de_aparici%C3%B3n_de_letras#Frecuencia_de_aparici%C3%B3n_de_letras_en_espa%C3%B1ol
      #letters_weights_map: &LETTERS_WEIGHTS_ES {K: 0.5, Ñ: 0.2, Q: 0.5, W: 0.2, X: 0.2, Y: 0.5}  # custom alternative
      letters_weights_map: &LETTERS_WEIGHTS_ES {A: 0.1253, B: 0.0142, C: 0.0468, D: 0.0586, E: 0.1368, F: 0.0069, G: 0.0101, H: 0.0070, I: 0.0625, J: 0.0044, K: 0.0002, L: 0.0497, M: 0.0315, N: 0.0671, Ñ: 0.0031, O: 0.0868, P: 0.0251, Q: 0.0088, R: 0.0687, S: 0.0798, T: 0.0463, U: 0.0393, V: 0.0090, W: 0.0001, X: 0.0022, Y: 0.0090, Z: 0.0052}
    en:
      letters: &LETTERS_EN [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
      # http://en.algoritmy.net/article/40379/Letter-frequency-English
      letters_weights_map: &LETTERS_WEIGHTS_EN {A: 0.08167, B: 0.01492, C: 0.02782, D: 0.04253, E: 0.12702, F: 0.02228, G: 0.02015, H: 0.06094, I: 0.06966, J: 0.00153, K: 0.00772, L: 0.04025, M: 0.02406, N: 0.06749, O: 0.07507, P: 0.01929, Q: 0.00095, R: 0.05987, S: 0.06327, T: 0.09056, U: 0.02758, V: 0.00978, W: 0.02360, X: 0.00150, Y: 0.01974, Z: 0.00074}

  output:
    # dirs/paths
    dir_rel: output/pages
    dir_rel_solution: output/pages_solution
    subdir_pages_html: pages_html
    subdir_pages_pdfa5: pages_pdfa5
    subdir_pages_pdfa5_merger: pages_pdfa5_merger
    subdir_pages_pdfa4: pages_pdfa4
    subdir_pages_pdfa4_merger: pages_pdfa4_merger
    # settings
    solution: True  # output also the solution alphasoup (an alphasoup just with the letters of the words)
    html: False  # output the html (and css) files, used to build the pdf documents
    pdfa5: False  # output many pdf DIN-A5 documents with 1-page each
    pdfa5_merger: True  # output one single pdf DIN-A5 document with many pages
    pdfa4: False  # output many pdf DIN-A4 documents with 2 DIN-A5 pages each
    pdfa4_merger: False  # output one single pdf DIN-A4 document with many pages, with DIN-A5 pages each

defaults:

  alphasoup: &ALPHASOUP
    ways: *WAYS_NORMAL
    rows: 12
    cols: 12
    words: []
    letters: *LETTERS_EN
    letters_weights_map: *LETTERS_WEIGHTS_EN

  html: &HTML
    title: null
    description: ''
    ways_allowed_text: &WAY_ALLOWED_TEXT ''
    word_cols: &WORD_COLS null
    word_per_col_max: &WORD_PER_COL_MAX 8
    word_checkers: &WORD_CHECKERS 0  # this is a long story... something regarding my grandmother... =D
    table_soup_px_max: &TABLE_SOUP_PX_MAX 600
    px_per_cell: &PX_PER_CELL 40
    td_soup_font_size_px: &TD_SOUP_FONT_SIZE_PX 20
    td_word_font_size_px: &TD_WORD_FONT_SIZE_PX 16

  pdfa5: &PDFA5
    options: &PDFA5_OPTIONS {
      'enable-local-file-access': '',  # https://stackoverflow.com/questions/73599970/how-to-solve-wkhtmltopdf-reported-an-error-exit-with-code-1-due-to-network-err
      'page-size': 'A5',
      'margin-top': '0.25in',
      'margin-right': '0.25in',
      'margin-bottom': '0.10in',
      'margin-left': '0.25in',
      'encoding': 'UTF-8'
    }

pages:

  - alphasoup:
      <<: *ALPHASOUP
      ways: *WAYS_NORMAL
      rows: 12
      cols: 12
      words:
        - SEWING
        - MACHINE
        - SHOES
        - COOKING
        - POTAJE
        - MOUNTAIN
        - EBOOK
        - MALLORCA
        - TABOO
        - GAMES
    html:
      <<: *HTML
      title: MY GRANNY
    pdfa5: *PDFA5

  - alphasoup:
      <<: *ALPHASOUP
      ways: *WAYS_NORMAL
      rows: 12
      cols: 12
      words:
        - VEGETABLES
        - FRUIT
        - MEAT
        - FISH
        - MILK
        - CHINESE
        - THAI
        - ITALIAN
        - SPANISH
        - FRENCH
    html:
      <<: *HTML
      title: FOOD
    pdfa5: *PDFA5

  - alphasoup:
      <<: *ALPHASOUP
      ways: *WAYS_ALL
      rows: 15
      cols: 15
      words:
        - FOOTBALL
        - SOCCER
        - BASKETBALL
        - RUGBY
        - GOLF
        - VOLLEYBALL
        - TENNIS
        - PINGPONG
        - PADEL
        - BADMINTON
        - SQUASH
        - BASQUEBALL
    html:
      <<: *HTML
      title: SPORTS
    pdfa5: *PDFA5

  - alphasoup:
      <<: *ALPHASOUP
      ways: *WAYS_ALL
      rows: 20
      cols: 20
      words:
        - POP
        - ROCK
        - COUNTRY
        - SOUL
        - DANCE
        - HIPHOP
        - JAZZ
        - CLASSIC
        - GUITAR
        - PIANO
        - ARPA
        - VIOLIN
        - DRUMS
        - TRIANGLE
        - XYLOPHONE
        - BASS
    html:
      <<: *HTML
      title: MUSIC
    pdfa5: *PDFA5
